name: Build and deploy for dev
on:
  push:
    branches: [ "develop" ]
jobs:
  ios-build:
    name: iOS Dev Build
    runs-on: self-hosted
    steps:
      - name: Show self-hosted machine information
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from dev branch
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Install npm dependency
        run: npm install
      - name: Cache cocoapods
        uses: actions/cache@v3
        with:
          path: /ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install pod dependency
        run: |
          cd ios
          pod install
      - name: Build iOS JS Bundle
        run: |
          npm run package-ios